-- CreateTable
CREATE TABLE "Espionage" (
    "id" SERIAL NOT NULL,
    "pid" INTEGER NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "detailLevel" INTEGER NOT NULL,
    "galaxy" INTEGER NOT NULL,
    "system" INTEGER NOT NULL,
    "position" INTEGER NOT NULL,
    "metal" INTEGER NOT NULL,
    "crystal" INTEGER NOT NULL,
    "deuterium" INTEGER NOT NULL,
    "smallCargo" INTEGER NOT NULL,
    "largeCargo" INTEGER NOT NULL,
    "lightFighter" INTEGER NOT NULL,
    "heavyFighter" INTEGER NOT NULL,
    "cruiser" INTEGER NOT NULL,
    "battleship" INTEGER NOT NULL,
    "colonyShio" INTEGER NOT NULL,
    "recycler" INTEGER NOT NULL,
    "espionageProbe" INTEGER NOT NULL,
    "bomber" INTEGER NOT NULL,
    "satalites" INTEGER NOT NULL,
    "destroyer" INTEGER NOT NULL,
    "deathstar" INTEGER NOT NULL,
    "battlecruiser" INTEGER NOT NULL,
    "rocketLauncher" INTEGER NOT NULL,
    "lightLaser" INTEGER NOT NULL,
    "heavyLaser" INTEGER NOT NULL,
    "gaussCanon" INTEGER NOT NULL,
    "ionCanon" INTEGER NOT NULL,
    "plasmaCanon" INTEGER NOT NULL,
    "smallShield" INTEGER NOT NULL,
    "largeShield" INTEGER NOT NULL,
    "antiBalisticMissile" INTEGER NOT NULL,
    "interplanetaryMissile" INTEGER NOT NULL,
    "metalMine" INTEGER NOT NULL,
    "crystalMine" INTEGER NOT NULL,
    "deuteriumSynthesizer" INTEGER NOT NULL,
    "solarPlant" INTEGER NOT NULL,
    "fusionPlant" INTEGER NOT NULL,
    "roboticsFactory" INTEGER NOT NULL,
    "naniteFactory" INTEGER NOT NULL,
    "shipyard" INTEGER NOT NULL,
    "metalStorge" INTEGER NOT NULL,
    "crystalStorage" INTEGER NOT NULL,
    "deteriumTank" INTEGER NOT NULL,
    "researchLab" INTEGER NOT NULL,
    "terraformer" INTEGER NOT NULL,
    "allianceDepot" INTEGER NOT NULL,
    "sensorPhalanx" INTEGER NOT NULL,
    "jumpGate" INTEGER NOT NULL,
    "missileSilo" INTEGER NOT NULL,
    "espionage" INTEGER NOT NULL,
    "computer" INTEGER NOT NULL,
    "weapons" INTEGER NOT NULL,
    "shield" INTEGER NOT NULL,
    "armour" INTEGER NOT NULL,
    "energy" INTEGER NOT NULL,
    "hyperspace" INTEGER NOT NULL,
    "combustionDrive" INTEGER NOT NULL,
    "impulseDrive" INTEGER NOT NULL,
    "hyperspaceDrive" INTEGER NOT NULL,
    "laserTech" INTEGER NOT NULL,
    "ion" INTEGER NOT NULL,
    "plasma" INTEGER NOT NULL,
    "igfn" INTEGER NOT NULL,
    "astropyhsics" INTEGER NOT NULL,
    "productionMaxMetall" INTEGER NOT NULL,
    "productionMaxCrystal" INTEGER NOT NULL,
    "productionMaxDeuterium" INTEGER NOT NULL,
    "graviton" INTEGER NOT NULL,

    CONSTRAINT "Espionage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Espionage_pid_key" ON "Espionage"("pid");

-- CreateIndex
CREATE UNIQUE INDEX "Espionage_galaxy_system_position_key" ON "Espionage"("galaxy", "system", "position");
