version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports:
          - "5432:5432"

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin-compose:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: "kejith@web.de"
          PGADMIN_DEFAULT_PASSWORD: "development"
      ports:
          - "16543:80"
      depends_on:
          - db


volumes:
  postgres-data:
